import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
import api from '../axios';

export default function Home() {
  const [data, setData] = useState({});

  useEffect(() => {
    (async function getData() {
      const { data } = await api.get('/api/profile');
      setData(data);
    })();
  }, []);

  console.log('data:', data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        Data:
        <div>{JSON.stringify(data, null, 2)}</div>
      </div>
    </div>
  );
}
